"""ローカル設定の例。assessment_config.py にコピーして設定する。"""
AI_PROVIDER = "oci_responses"
OPENAI_MODEL = "gpt-5.6-terra"
COMPARTMENT_ID = ""
GENAI_MODEL_ID = ""
GENAI_ENDPOINT = ""
OCI_REGION = ""
OCI_GENAI_PROJECT_OCID = ""
OCI_CONFIG_FILE = "~/.oci/config"
OCI_PROFILE = "DEFAULT"
REASONING_EFFORT = "medium"
